- name: "Install repos"
  package:
    name: 
      - centos-release-scl-rh
      - epel-release
    state: latest
    update_cache: yes

- name: "Install Ruby and OS packages"
  package:
    name: 
      - "@Development tools"
      - rh-ruby26-ruby.x86_64
      - rh-ruby26-ruby-devel.x86_64 
      - epel-release
      - libxml2-devel
      - python-psycopg2
      - policycoreutils-python
      - python2-pip
      - nodejs
      - mc
    state: latest
    update_cache: yes
