- name: "Install Nginx"
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_yum_repo_enabled: false

- name: "Replace Nginx config"
  template:
    src: 'nginx.conf.j2'
    dest: "/etc/nginx/nginx.conf"

- name: "Allow Web on firewall"
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - https
    - http

- name: Allow HTTP in SElinux
  shell: semanage permissive -a httpd_t

- name: "Start and enable Nginx"
  service:
    name: nginx.service
    enabled: yes
    state: restarted
